reflex-frp/reflex-dom

reflex-dom.cabal
...which was referring to `reflex`, not `reflex-dom`.
=> Fix `source-repository` entry in reflex-dom

src/Reflex/Dom/Widget/Basic.hs
It is unlikely one would like a button press to submit the content of a form. This patch changes the default type of the button widget from "submit" to "button".
=> Prevent buttons from submitting form contents

src/Reflex/Dom/Xhr.hs
The `newXMLHttpRequest` function presented two issues:
1. Creating an XHR connection in at least one browser (Chrome) blocks
while creating the connection, despite the result coming back
asynchonrously. This creates a certain lag when calling the function,
and thus also causes event handlers to block which delays subsequent
event handlers from running. A simple example is an event containing a
request; there are two handlers for this event (1) a spinner, (2) one
that makes a connection. The one that makes a connection will stop the
spinner from activating. If there is sufficient network delay, the
spinner won't appear for some 300ms to some seconds, defeating the
purpose of a spinner in the first place.
2. Handling an error. Related to the first, creating the XHR connection
blocks but can …
=> Make newXMLHttpRequest async, handles errors (#34)

src/Reflex/Dom/Widget/Basic.hs
This change uses `getClientX` in place of `getX` in the implementation of `getMouseEventCoords`.
Some research:
`getX` calls a javascript MouseEvent method that has an experimental flag in the [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/x) and is not supported under Firefox.
An [example](http://web.mit.edu/greghale/Public/mousenew2/) compiled against `getClientX`/`getClientY`  works under Chome & Firefox. The [same example](http://web.mit.edu/greghale/Public/mouseold/) compiled with the version of `getMouseEventCoords` using `getX`/`getY` works in Chrome but not in Firefox.
It's more common for me to want Mouseevent coordinates relative to the element catching the event, rather than relative to the corner of the client. There are `uiLayerX` and …
=> Prefer getClientX over getX

src/Reflex/Dom/Widget/Basic.hs
The old code caused a rebuild of an entry whenever it is part of the `valChanged` map for the first time.
=> consider initialVals when calculating sentVals in listWithKeyShallowDiff

reflex-dom.cabal
My local tests show no problem with aeson-0.11 and unfortunately I haven't found proper tests to be 100% sure
=> Enabled support for aeson-0.11

src-ghc/Reflex/Dom/Xhr/Foreign.hs
Together with https://github.com/reflex-frp/reflex-dom/pull/83 both ghcjs and ghc will have `IsXhrPayload` instances for both `String` and `Text`
=> Add IsXhrPayload instance for String under GHC

src-ghc/Reflex/Dom/WebSocket/Foreign.hs, src-ghcjs/Reflex/Dom/WebSocket/Foreign.hs, src/Reflex/Dom/WebSocket.hs
This PR makes the websocket message type polymorphic so that messages can be sent in either text of binary form. It's also possible to use 'Either Text ByteString' to allow switching between text and binary formats for the same websocket.
=> Allow sending websocket messages in binary or text

src/Reflex/Dom/Widget/Basic.hs
That was fixed in c5f7300431ab12140e054555808ead799f7af43e but somehow comment didn't get deleted and is confusing
=> Remove not longer valid TODO

src/Reflex/Dom/Old.hs
Without it functions like `elWith'` are just unusable
=> Export ElConfig

src/Reflex/Dom/Builder/Class.hs
The form of the constraint should only depend on the functor,
and never on the arguments. This means that the constraint
may well need to be expressed using an auxiliary class, but
everything should make more sense.
=> Make the Functor1Constraint family sensible

src/Reflex/Dom/Old.hs
Making `MonadWidget` a type synonym forced users to include
mysterious language extensions. Making it first-class gets rid
of that requirement. Using a type synonym to express its
constraints avoids excess source code.
=> Turn MonadWidget back into a class

src/Reflex/Dom/Builder/Class.hs
This reverts commit cbf2fb08c32b1e588d72a2a9e85e78f794b8487a.
I changed my mind. It's actually possible to slide in either
direction using auxiliary classes, and it's not so clear that
I slid it in the direction of clarity. Sorry for the confusion.
=> Revert "Make the Functor1Constraint family sensible"

src/Reflex/Dom/Xhr.hs
encodeToTextBuilder was moved to Data.Aeson.Text in version 1.0.0.0
(The CPP pragma wasn't in alphabetical order before)
=> Import correct aeson module

src-ghc/Reflex/Dom/Internal/Foreign.hs, src-ghc/Reflex/Dom/WebSocket/Foreign.hs, src-ghcjs/Reflex/Dom/WebSocket/Foreign.hs, src/Reflex/Dom/WebSocket.hs
Extend websocket API with the following things:
* allow websockets to be closed via event
* add option to control reconnect behavior
* expose error and close events
I had no success making chrome pass actual CloseEvent values downstream. Seems to always be False for wasClean and 1006 for code, even though it does echo back correct values on server initiated close. Not sure if this is a bug in the code somewhere that only displays in Chrome or maybe a "security feature". Firefox and GHC do seem to work well.
I think the only app code that should need refactoring is that using `WebSocketConfig` constructor directly instead of `def`.
Any suggestions most welcome.
Also, now that I think of it some more, it may be misleading that trying to close a websocket by default will cause it to …
=> Improve websocket API

src/Reflex/Dom/Old.hs
`buildElementNS` is useful and missing
=> Export `buildElementNS`

src/Reflex/Dom/Time.hs
I found the tickLossyFrom' function useful to avoid the widgetHold that would have been necessary with the existing tickLossyFrom.  In my case I only needed for `t0`, but I figured we might as well go the whole way and include `dt` in the event as well.
Name bikeshedding welcome.
=> Generalization of tickLossyFrom

src/Reflex/Dom/Builder/Class/Events.hs, src/Reflex/Dom/Builder/Immediate.hs
Previously, the `Touchmove` event returned `()`, now it returns `[(Int, Int)]`.
=> Touchmove event now returns a list of coordinates

src/Reflex/Dom/Builder/Class/Events.hs, src/Reflex/Dom/Builder/Immediate.hs
Note that this, like the TouchEvent work that preceded it, doesn't fix the GHC implementation or put the alternative implementations in the src-ghc and src-ghcjs trees.
Once the jsaddle branch is merged, the ghc implementation should be straightforward and I'll move things around as necessary.
=> Expose more TouchEvent information

reflex-dom.cabal
Currently e.g. stack outputs a warning like:
```
Warning: The following modules should be added to exposed-modules or other-modules in /home/qrilka/ws/h/reflex-huge-table/.stack-work/downloaded/G129R_XZQgTL/reflex-dom.cabal:
- In the library component:
Reflex.Dom.Builder.Class.TH
Missing modules in the cabal file are likely to cause undefined reference errors from the linker, along with other problems.
```
=> Added missing module to cabal file

reflex-dom.cabal
For latest stackage LTS to build reflex, reflex-dom you'll need dependent-sum 0.4 so ease up dependency to allow build
=> ease up deps

Quickref.md
After discussion on StackOverflow [[1](http://stackoverflow.com/questions/38268962/a-single-svg-element-with-reflex-frp)] I learned about the `elDynAttrNS'` which does not appear in the [Quick Reference](https://github.com/reflex-frp/reflex-dom/blob/develop/Quickref.md).  One line fix.
=> info on elDynAttrNS' tag

reflex-dom-core/src/Reflex/Dom/WebSocket/Foreign.hs
This avoids going from Text -> String -> JSString to simply Text ->  JSString
Also even cheaper if using text-jsstring patches
=> Don't convert to String when sending Text data through websockets.

reflex-dom-core/src/Foreign/JavaScript/TH.hs, reflex-dom-core/src/Reflex/Dom/Builder/Class.hs, reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs, reflex-dom-core/src/Reflex/Dom/Builder/InputDisabled.hs, reflex-dom-core/src/Reflex/Dom/Builder/Static.hs, reflex-dom-core/src/Reflex/Dom/Modals/Base.hs, reflex-dom-core/src/Reflex/Dom/Widget/Basic.hs, reflex-dom-core/src/Reflex/Dom/Widget/Input.hs, reflex-dom-core/src/Reflex/Dom/Widget/Lazy.hs, reflex-dom/examples/sortableList.hs
Also deals with the renaming of `MonadAdjust` in `reflex`.  There is a companion PR against `reflex` [here](https://github.com/reflex-frp/reflex/pull/121).
=> Moves the collection management functions to `reflex`.

Quickref.md
The deleted content has been moved to the QuickRef.md in the `reflex` repository in a [companion PR](https://github.com/reflex-frp/reflex/pull/137).
=> Adjusts Quickref.md to reflect recent changes

reflex-dom-core/src/Reflex/Dom/Builder/Class.hs, reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs, reflex-dom-core/src/Reflex/Dom/Builder/InputDisabled.hs, reflex-dom-core/src/Reflex/Dom/Builder/Static.hs, reflex-dom-core/src/Reflex/Dom/Widget/Basic.hs
This also included moving generalizations of `dyn` and `widgetHold` across to `reflex` and breaking out a `NotReady` class from the `DomBuilder` class.
There is a companion PR in the `reflex` repository [here](https://github.com/reflex-frp/reflex/pull/138).
=> Moves Workflow across to reflex

reflex-dom-core/src/Reflex/Dom/Widget/Input.hs
These are certainly handy for catching keys which don't produce characters (notably the escape key).
=> Add 'keydown' and 'keyup' to match 'keypress'

reflex-dom-core/reflex-dom-core.cabal, reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs
By using this function from ghcjs-dom we get the ghcjs-base
implementation that is simpler on ghcjs.  On ghc we get the new
jsaddle version that has the same optimization we have now, but
handlers are shared with anything else that uses `inAnimationFrame`.
=> Use inAnimationFrame from ghcjs-dom.

reflex-dom/default.nix, reflex-dom/reflex-dom.cabal, reflex-dom/src/Reflex/Dom/Internal.hs
I'm new to Reflex, feel free to provide any feedback. This change was originally motivated by [this](https://github.com/reflex-frp/reflex-platform/pull/222#issuecomment-360186869) [discussion](https://github.com/reflex-frp/reflex-platform/pull/227#issuecomment-361451491).
It enables the use of jsaddle-warp as default when compiled with GHC.
---
The flag `use-warp` controls this. Because it is enabled by default,
the user would see a warp server in place of webkit/gtk frontend
when when compiling the frontend in GHC.
Port number for the warp server is determined from the environment
variable `JSADDLE_WARP_PORT`, with a default value of 3003. The
port number will be printed to stdout by `run` so that user would
know where they can access the app.
=> jsaddle-warp support for `run` and friends

reflex-dom/java/org/reflexfrp/reflexdom/MainWidget.java
Find a picture of the default [here](https://i.stack.imgur.com/9qndO.png). It is really not that pretty and more importantly, it is not shown in normal Chrome. This PR replaces the default to make it behave like a standard Chrome. (No image is shown)
=> Disable default video poster in WebView.

reflex-dom/java/org/reflexfrp/reflexdom/MainWidget.java
We simply forward everything that is not https:// http:// or file:// to Android.
Are there any better ways for knowing what URI schemes should be opened in the WebView directly? 
This PR makes links like whatsapp:// or tg:// sms:// mailto:// and similar work, as the webview does not know how to handle them. We make them work, by simply passing them on to Android.
=> Handle external urls from WebView

reflex-dom/reflex-dom.cabal
For backwards compatibility with things that rely on webkit2gtk
being the default backend with ghc.
Addresses https://github.com/reflex-frp/reflex-platform/issues/231#issuecomment-362597152
=> use-warp should be disabled by default

reflex-dom/cbits/MainWidget.c, reflex-dom/java/org/reflexfrp/reflexdom/MainWidget.java
From Android 6 on we have to ask for permissions at runtime. This commit
together with the [PR](https://github.com/reflex-frp/reflex-platform/pull/242) for the reflex-platform asks the user for permission for
accessing camera and microphone as it is required from Android 6 onwards.
When the Webview asks for permissions, we check whether we have the
corresponding Manifest permissions - if so, we simply grant the request. If not
we ask the user for permission. The implementation is also compatible with
Android 5 as we simply grant access in that case.
The split up into a PR for reflex-dom and reflex-platform is unfortunately
necessary because of the way we get the user's answer in Java: By means of an
overriden method of Activity.
=> Ask user for permissions.

reflex-dom-core/src/Reflex/Dom/WebSocket.hs, reflex-dom-core/src/Reflex/Dom/WebSocket/Foreign.hs
- Un-hardcode the `[]` in `DOM.newWebSocket url []`
- Add extra config field
Backwards compatible as long as the config constructor isn't used with positional arguments.
=> Add support for websocket protocols

reflex-dom-core/reflex-dom-core.cabal
allow aeson 1.3.x  (in order to be compatible with stack lts-12.3)
=> allow aeson 1.3.x

reflex-dom/src/Reflex/Dom/Internal.hs
This change only affects iOS which was failing to find assets relative
to the main bundle resource path which is the expected location for the
it to be placed.
TODO: upstream this to jsaddle-wkwebview
=> Fix iOS baseUrl

reflex-dom-core/default.nix
to match the plaform for which it is buildable
=> addGcTestDepends should noop on cross and ghcjs

reflex-dom-core/src/Reflex/Dom/Widget/Input.hs
this gets rid of the usage of `getFilesUnchecked` reported in #274 
Fixes #274
=> Reuse files from inputElement in fileInput

reflex-dom-core/reflex-dom-core.cabal, reflex-dom-core/src-chromedriver-utils/Test/Util/ChromeFlags.hs, reflex-dom-core/src-chromedriver-utils/Test/Util/UnshareNetwork.hs, reflex-dom-core/test/gc.hs, reflex-dom-core/test/hydration.hs
This seems to fix the flakiness in the hydration tests in three ways:
* disabling the `traverseIntMapWithKeyWithAdjust` tests which fail intermittently (possibly due to an underlying reflex bug)
* replacing all the `threadDelay`s with a retry combinator which attempts an assertion repeatedly with small delays up until some rather large timeout (~30s)
* setting up a new network namespace at the beginning of the tests so we can use fixed port numbers with no risk of conflicting with other processes
=>  Make hydration tests reliable

reflex-dom-core/reflex-dom-core.cabal, reflex-dom-core/src/Foreign/JavaScript/TH.hs, reflex-dom-core/src/Reflex/Dom/Prerender.hs, reflex-dom-core/test/hydration.hs
That way we never need lie about what constraints we have in an (function) argument to make it uncallable.
TODO test rebase builds, and test result
=> Lift Prerender method constraints onto class instead

reflex-dom-core/ChangeLog.md, reflex-dom-core/default.nix, reflex-dom-core/reflex-dom-core.cabal, reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs, reflex-dom-core/src/Reflex/Dom/Main.hs, reflex-dom-core/test/hydration.hs, reflex-dom/ChangeLog.md, reflex-dom/default.nix, reflex-dom/reflex-dom.cabal
In an attempt to fix hydration in the presence of executable-config, we add the option of marking tags with a "data-hydration-skip" attribute, and remove the "data-ssr" attribute from static rendering. Prior to this, tags without the "data-ssr" attribute would be skipped over by hydration, now that only occurs for tags with "data-hydration-skip", and everything else is matched. (We're still not yet checking to ensure attributes are equal.)
This seems to fix the interaction alongside the PR I'm about to make on Obelisk.
=> Hydration fixes

reflex-dom-core/ChangeLog.md, reflex-dom-core/reflex-dom-core.cabal, reflex-dom-core/src/Reflex/Dom/Builder/Hydratable.hs, reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs, reflex-dom-core/src/Reflex/Dom/Builder/InputDisabled.hs, reflex-dom-core/src/Reflex/Dom/Builder/Static.hs, reflex-dom-core/src/Reflex/Dom/Core.hs, reflex-dom-core/src/Reflex/Dom/Prerender.hs, reflex-dom-core/test/hydration.hs
https://github.com/reflex-frp/reflex-dom/pull/317/commits/9bd809bc00f88834f23b427e3d2adc0cb0fb09b1 removed data-ssr in favour of explicitly skipping certain elements. Allowing explicit skipping is a good change, but the lack of implicitly skipping things which _aren't_  produced by the static renderer causes somewhat unsolvable issues when using certain external JS libraries, for example, the ace editor, which injects some `style` tags into the head. This PR supports both explicit and implicit skipping of elements during hydration.
=> Skip hydration for elements with data-ssr attribute

dep/reflex-platform/github.json
This improves cabal2nix for mobile, and is needed for https://github.com/reflex-frp/reflex-dom/pull/329
=> Bump reflex-platform for tests

reflex-dom-core/reflex-dom-core.cabal
This does not introduce anything that actually _uses_ the new features of `constraints-0.11.*` as it only changes the version bounds in the Cabal file. Compiling `reflex-dom-core` with the new version did not appear to introduce any build-time warnings or errors. The `constraints-extras` package (which has Obsidian maintainers) has also made this same change without any apparent issues and therefore I believe it is reasonably safe.
=> Loosen constraints version bounds for reflex-dom-core.

default.nix
If we call `callPackage` ourselvess around the `callCabal2nix`, fewer
and unexpected things alone can be overridden---just the packages we
used in the manual `overrideCabal`s. This new way, those package cannot be
overridden, but at least the default cabal2nix-generated arguments scan.
That's the better trade-off.
The real issue  `callPackage` arg sniffing breaks eta expansion, which
really sucks.
=> Fix overriding mkDerivation

release.nix
It was unused and way more confusing than I thought.
=> Skip "variations" in release.nix

reflex-dom-core/ChangeLog.md, reflex-dom-core/src/Reflex/Dom/Widget/Basic.hs
These were added in 0.5.3, but ended up being a burden on users. For
now, they will remain in Reflex.Dom.Widget.Basic until a better
alternative emerges. A separate widget toolkit may eventually contain
these opinionated widgets.
Note that deprecations from Reflex.Dom.Widget.Input in 0.5.3 still
stand.
=> Remove deprecation warnings for Reflex.Dom.Widget.Basic

reflex-dom-core/ChangeLog.md, reflex-dom-core/reflex-dom-core.cabal, reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs, reflex-dom-core/src/Reflex/Dom/Builder/Static.hs, reflex-dom-core/test/hydration.hs
Thanks to @tomsmalley for helping me understand this better.
The tests confirm that the crash is fixed. Reverting the fix but keeping the tests yields
```
A JavaScript exception was thrown! (may not reach Haskell code)
TypeError: Cannot read property 'nextSibling' of null
hydration: JSException
```
=> Fix hydration runWithReplace when beginning marker can't be found

reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs
This simplifies things, and avoids creating extra events.
/cc @tomsmalley @ryantrinkle
=> Avoid runWithReplace call when hydrating

reflex-dom-core/ChangeLog.md, reflex-dom-core/src/Reflex/Dom/Builder/Hydratable.hs, reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs
This change means consumers (such as obelisk) don't need to hardcode strings
=> Export hydration attributes

reflex-dom-core/src/Reflex/Dom/Xhr.hs
CI doesn't seem to build with USE_TEMPLATE_HASKELL = false
=> Fix type of xhrResponse_headers lens when TH is disabled

reflex-dom-core/reflex-dom-core.cabal
I have confirmed that this compiles with those versions via nixpkgs.
I would very much appreciate a hackage revision with these version bounds updated.
=> Bump version bounds

reflex-dom-core/src/Reflex/Dom/Prerender.hs
=> Add `now` to the `MonadHold` instance for `UnrunnableT`

reflex-dom/reflex-dom.cabal
As mentioned in #414, removing these restrictions allows reflex-dom to build on Windows.
Since there isn't any test suite for reflex-dom and the test suite for reflex-dom-core is currently incompatible with Windows, the best I could do for testing is try to use reflex-dom to make [an example site I found](https://github.com/typeable/blog-posts-ru/tree/680581203f0fd5f7fe0714d9d8778e9426010ea7/reflex-todo), since the built-in example is broken (see #422).
The site appeared to work fine on Chrome, but was completely unresponsive on Firefox, though I'm unsure if this is a Windows issue or an issue for reflex-dom in general.
Either way I think the best solution is to remove this restriction and let any windows bugs bubble up as issues, rather than barring a user from compiling under windows …
=> Remove OS restriction for use-warp mode
