reflex-frp/reflex-dom

src-ghcjs/Reflex/Dom/Xhr/Foreign.hs
src/Reflex/Dom/Internal.hs
src/Reflex/Dom/Widget/Basic.hs
src/Reflex/Dom/Xhr.hs

Hi Ryan, I've fixed some importing and type conflict problems so that the code can be compiled and installed. Hope it's right fixes.

Add some imports and functions to transform the data format

---

src/Reflex/Dom/Xhr.hs

This adds a function to create an `XhrRequest` out of an url and a value that can be converted to JSON.
This doesn't work yet though. Aeson only supports encoding to `ByteString` and there seems to be no good way to convert a `ByteString` to a `String`. I could only find `show` and `unpack` from Data.ByteString.Char8 which truncates characters to 8 bits.
Maybe there's a function I'm missing or maybe reflex-dom should use `ByteString` for the body instead of `String`.

Add `postJson` – WIP

---

README.md

I think that many people miss the link to the slides in the video, i also missed it at first

add link to the slides

---

src/Reflex/Dom/Widget/Basic.hs

current behaviour causes flickering

remove old & add new DOM in on render frame in dyn/widgetHold

---

src/Reflex/Dom/Widget/Basic.hs

I wrote this in one of our projects and it's universal enough to belong here I think.

Add mapWorkflow

---

src/Reflex/Dom/Widget/Basic.hs

This is usually the function that people will want, right?

Suggest function for flattening results of 'dyn'

---

reflex-dom.cabal
src-ghcjs/Reflex/Dom/WebSocket/Foreign.hs
src/Reflex/Dom/WebSocket.hs

Also fixes exception happening while sending a message when ws is in 'connecting' state
e923366 allows receiving non-binary messages from server. (can split the two commits as separate PRs if needed)

Buffering outgoing websocket messages when ws not open

---

src/Reflex/Dom/Xhr.hs

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#xmlhttprequest-withcredentials

allow use of withCredentials on XMLHttpRequest

---

default.nix
reflex-dom.cabal
src/Reflex/Dom.hs
src/Reflex/Dom/Builder/Static.hs
src/Reflex/Dom/Internal.hs

Add Static Builder

---

src/Reflex/Dom/Widget/Input.hs

The dropdown change event was never being fired.

Fix dropdown select event bug

---

src/Reflex/Dom/Widget/Basic.hs

`elDynClass` is a logical extension of `elClass` which can be used with a Dynamic class string. Prime versions of this and `elClass` have also been added. The `el` family of functions has also been reordered.

Add elDynClass convenience function.

---

Quickref.md

Update the QuickRef by replacing String with Text and adding the 'a' param to XhrRequest and XhrRequestConfig.

Update QuickRef 

---

src-ghcjs/Reflex/Dom/Xhr/Foreign.hs

since use Text everywhere, i think this instance is necessary.
is JSString instance necessary?
first time to send a PR,if i do sth wrong, let me know.

add IsXhrPayload instance of Text

---

src/Reflex/Dom/Builder/Immediate.hs
src/Reflex/Dom/Old.hs

per 2016-09-03 reflex-frp irc discussion.

replaced HTMLElement with Element as needed

---

src/Reflex/Dom/Widget/Basic.hs

In the process of upgrading to the latest `reflex-dom`, I found that `listWithKey` doesn't work as expected. I was previously using a definition based on `widgetHold` and #13, because the released one did not work. The following works for me with the latest `reflex-dom` in `develop`:
```haskell
listWithKey
:: (Ord k, MonadWidget t m)
=> Dynamic t (Map k v)
-> (k -> Dynamic t v -> m a)
-> m (Dynamic t (Map k a))
listWithKey mapD mkChild = widgetHold' child mempty mapEv
where
child m = forWithKeyA m $ \k v ->
mkChild k =<< holdDyn v (fmapMaybe (Map.lookup k) mapEv)
mapEv = updated mapD
widgetHold'
:: (DomBuilder t m, MonadHold t m)
=> (a -> m b)
-> a
-> Event t a -> m (Dynamic t b)
widgetHold' f edef e = widgetHold (f edef) (f <$> e)
```
The problem is that I'm not seeing any updates to a …

Use listHoldWithKey in listWithKey

---

.gitignore

Added them by mistake, sorry about that.

Remove codex.tags and ignore

---

src/Reflex/Dom/Builder/Class/Events.hs
src/Reflex/Dom/Builder/Immediate.hs

Touchstart, Touchend, Touchcancel all return list of coordinates

---

src/Reflex/Dom/Xhr.hs

I reogranized the documentation into sections and added an example of creating a request, performing it and outputting the response as a string.

Organized XHR documentation into sections and added an example.

---

reflex-dom-core/reflex-dom-core.cabal
reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs
reflex-dom-core/src/Reflex/Dom/Main.hs
reflex-dom-core/src/Reflex/Dom/Modals/Base.hs
reflex-dom-core/src/Reflex/Dom/Old.hs
reflex-dom-core/test/gc.hs

merged develop into cg-is-pathWidget

Cg is path widget

---

reflex-dom-core/src/Reflex/Dom/Location.hs

Ideas/Todo:
* Include saved state from `popState`.
* Include minimal API for changing the window location and saving state via `pushState`.
* Include helper for URL query part (e.g. `getLocationQuery`). This could include parsing for the arguments.
* Figure out how to properly handle exceptions with `decodeURI`.

WIP: Fuller API for browser history

---

reflex-dom-core/src/Reflex/Dom/Widget/Basic.hs

Somehow this got lost in my reworking and/or rebasing.

Re-exports the collection code

---

reflex-dom/java/org/reflexfrp/reflexdom/MainWidget.java

It should be fine to grant permissions if the origin is a file:// url.
This is needed for getUserMedia to work.

Android: Handle onPermissionRequest

---

reflex-dom/src/Reflex/Dom/Internal.hs

Resolves #222.  It depends on https://github.com/ghcjs/jsaddle/pull/60.
Together these two PRs should be a clean solution for reflex-frp/reflex-platform#209

Use *run* instead of *runFile* for WKWebView

---

reflex-dom-core/src/Foreign/JavaScript/Orphans.hs
reflex-dom-core/src/Foreign/JavaScript/TH.hs

Partial revert to get compiling on reflex after https://github.com/reflex-frp/reflex/pull/220

Update for PerformEventT as a transformer revert

---

reflex-dom-core/src/Reflex/Dom/Core.hs

Fixes
```
haddock: internal error: internal: extractDecl
CallStack (from HasCallStack):
error, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:1097:12 in main:Haddock.Interface.Create
```

Fix haddocks build

---

reflex-dom-core/src/Reflex/Dom/Core.hs
reflex-dom/src/Reflex/Dom.hs

similar to https://github.com/reflex-frp/reflex-dom/pull/263 but for reflex-dom

Fix haddocks for reflex-dom

---

reflex-dom/reflex-dom.cabal

Fix useWarp on macos

---

README.md

Fix path reference from reflex-platform

---

reflex-dom-core/src/Foreign/JavaScript/TH.hs
reflex-dom-core/src/Reflex/Dom/Prerender.hs

Fixes some issues that crept in with #294

Fix errors introduced by recent JSM and UnrunnableT changes

---

FAQ.md

Resolves #211 with a FAQ rather than helper functions, as they only seem to be marginally better than the existing solution, and introduce some issues of their own. It seems like what we really want is a better underlying API, and the better solution for now is to add documentation for anyone who needs this.

Add FAQ for configuring DOM events

---

reflex-dom-core/reflex-dom-core.cabal
reflex-dom-core/src/Reflex/Dom/Xhr.hs

Make XhrHeaders case insensitive

---

reflex-dom-core/ChangeLog.md
reflex-dom-core/reflex-dom-core.cabal
reflex-dom/ChangeLog.md
reflex-dom/reflex-dom.cabal

Bump Reflex to include 0.7

---

reflex-dom-core/src/Reflex/Dom/Widget/Resize.hs

Hey there, thanks for this awesome library, it's been fun digging into it all. Proposing this change since I was surprised the builtin resize event did not actually include any details about the resize. My use case involves animating SVGs and knowing the dimensions of the generated `div` is necessary to ensure all the SVGs are visible on resize.

Return dimensions in resize event.

---

reflex-dom-core/ChangeLog.md
reflex-dom-core/reflex-dom-core.cabal
reflex-dom-core/src/Reflex/Dom/Builder/Class.hs
reflex-dom-core/src/Reflex/Dom/Builder/Immediate.hs
reflex-dom-core/src/Reflex/Dom/Builder/Static.hs
reflex-dom-core/src/Reflex/Dom/Main.hs
reflex-dom-core/src/Reflex/Dom/Widget/Lazy.hs
reflex-dom-core/test/hlint.hs
reflex-dom-core/test/hydration.hs

This is part of the nixos-20.09 upgrade. It builds from the WIP reflex-platform branch, which I don't yet have a link for.

Tiny test fixes

---

reflex-dom-test-selenium/src/Reflex/Dom/Test/Selenium.hs

fix a typo: unshareNetork

---

reflex-dom-test-selenium/reflex-dom-test-selenium.cabal
reflex-dom-test-selenium/src/Reflex/Dom/Test/Selenium.hs
reflex-dom/reflex-dom.cabal

Built on top of https://github.com/reflex-frp/reflex-dom/tree/fix-android-build-ghc810

Merge Android Build Fix
